name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: unit test
        run: pnpm --filter react-pocket-form test:unit

      - name: cypress test
        run: pnpm --filter react-pocket-form test:cypress
